# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: version check
        run: |
          export CHNGVER=$(grep -P -o '(?<=## \[).*(?=\])' -m1 CHANGELOG.md); 
          echo "CHANGELOG VERSION: $CHNGVER"
          export INITVER=$(grep -P "__version__ = '.*?'" riscv_isac/__init__.py | awk '{print $3}'|sed "s/'//g"); 
          echo "INIT VERSION: $INITVER"
          export TAGVER=$(git describe --tags --abbrev=0);
          echo "TAGVER: $TAGVER"
          if [ "$CHNGVER" = "$INITVER" ]; then
              echo "Versions are equal in Changelog and init.py."
          else
              echo "Versions are not equal in Changelog and init.py."
              exit 1
          fi
          if [ "$CHNGVER" = "$TAGVER" ]; then
              echo "Versions are equal in Changelog and current tag."
              exit 1
          else
              echo "Versions are not equal in Changelog and current tag. Good."
          fi
